[package]
name = "http-thing"
version = "0.1.0"
edition = "2021"
description = "Simple HTTP routing"
license-file = "LICENSE"
keywords = ["http", "tcp"]

[dependencies]
httparse = "1.9.5"
log = "0.4.24"
thiserror = "2.0.11"

[dev-dependencies]
clang_log = "2.0.5"
